#!/bin/bash

# Usage: tf_idf_search.sh [queryfile] [resultfile] [indexfile] [dictfile]
# where
# [queryfile] is the path to the file containing queries
# [resultfile] is the path to the output file where results will be stored
# [indexfile] is the path to the index file generated by invidx_cons
# [dictfile] is the path to the dictionary file generated by invidx_cons

if [ $# -ne 4 ]; then
    echo "Usage: $0 [queryfile] [resultfile] [indexfile] [dictfile]"
    exit 1
fi

QUERYFILE=$1
RESULTFILE=$2
INDEXFILE=$3
DICTFILE=$4

# Run the TF-IDF search Python script
python3 tf_idf_search.py $QUERYFILE $RESULTFILE $INDEXFILE $DICTFILE